<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="hanwenlu" name="pytest" skipped="0" tests="1" time="3.777" timestamp="2019-12-18T16:12:37.316249"><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 196, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 246, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 270, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pytest_rerunfailures.py&quot;, line 176, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\runner.py&quot;, line 90, in runtestprotocol
    rep = call_and_report(item, &quot;setup&quot;, log)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\runner.py&quot;, line 184, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;E:\yuxichen\pytest\conftest.py&quot;, line 74, in pytest_runtest_makereport
    capture_screenshot(case_name)
  File &quot;E:\yuxichen\pytest\conftest.py&quot;, line 123, in capture_screenshot
    driver.save_screenshot(image_dir)
NameError: name &apos;driver&apos; is not defined</error></testcase></testsuite></testsuites>